### PR TITLE
Make heat-equation example run on GPUs

### PR DESCRIPTION
**Pull request by upsj**
This PR adds GPU support to the heat-equation example.

### CODE REVIEW

**Review by yhmtsai — APPROVED** [review]
LGTM. Does adding executor selection in this example make sense?

**Comment by upsj** [comment]
I think since this is meant as an example for a tutorial setting, keeping it as simple as possible is desirable (similar to the minimal-cuda-solver example). But maybe @hartwiganzt also has an opinion about that.

**Review by pratikvn — APPROVED** [review]
LGTM!

**Review by Slaedr — CHANGES_REQUESTED** [review]
Looks good; just one concern. Looks like this example can no longer be run without a NVidia GPU. Maybe it would be nice to enable different executors based on a command line argument, or at least the omp executor along with cuda.

**Comment by upsj** [comment]
@Slaedr Mike had the same concern, though I think keeping this as simple as possible for an introductory tutorial is also important. Maybe let's discuss that tomorrow.

**Comment by Slaedr** [comment]
Okay, I understand. Even for the tutorial, maybe it's nice to just select between `omp` and `cuda` (not bother with the whole `map`)?

**Comment by yhmtsai** [comment]
Could you check whether using cg without precondition on coo matrix works or not?
For dpcpp porting PR (not just in one branch), I plan to work dense->coo->cg first.
Thus, if it is fine, could you also change it?

**Review by Slaedr — APPROVED** [review]
So I'll leave it to you to decide about the executor then, though I'd personally like to see some (simplified) form of backend selection to at least enable running on CPU. In any case, thanks for the nice artistic example!

**Pull request merged**
