### PR TITLE
Bump copyright year to 2021

### PR DESCRIPTION
**Pull request by yhmtsai**
This PR bumps the copyright year to 2021.
Edit the `LICENSE` and `make format`

@upsj do I also need to change the year of gdb-ginkgo.py? or does it need to wait the pretty-printers

Happy new year!

### CODE REVIEW

**Review by tcojean — APPROVED** [review]
LGTM.

Somehow, the bot wasn't able to detect that DPC++, OMP and Reference files changed. I think it's an issue with how the regex is written?

**Review by upsj — APPROVED** [review]

**Comment by tcojean** [comment]
Too bad, using the `reviewers` github group doesn't work as we would expect: when one person approves, it's like the whole group approved. Whereas what we want is "get any two persons from the group to review this".

**Comment by upsj** [comment]
Relating to the gdb pretty printers: I don't think we necessarily need to update the license date there unless we modify the file itself. I think this is only important for files which get formatted automatically.

**Comment by tcojean** [comment]
label!

**Comment by yhmtsai** [comment]
Is the bot from develop not this branch?

**Comment by upsj** [comment]
The issue is that the bot only takes the first page of changed files for simplicity, since these huge diffs are rare, I think we can ignore this issue.

**Comment by tcojean** [comment]
Yes I realized later that would not update it here. And I see, I thought that the issue would be that bash somehow interprets and gobbles the `^` in its own way, like it can happen to `!` and other characters sometimes.

**Review by hartwiganzt — APPROVED** [review]

**Review by pratikvn — APPROVED** [review]
LGTM!

**Comment by yhmtsai** [comment]
The maximum of one page is 100 even if we specify it `&per_page=1000` in `label.sh`

**Comment by yhmtsai** [comment]
label!

**Comment by yhmtsai** [comment]
format!

**Comment by yhmtsai** [comment]
Maybe I do the `format` too quickly such that github action only takes the original commit not the github-bot-format commit.
Windows: https://github.com/ginkgo-project/ginkgo/actions/runs/468671383
Mac: https://github.com/ginkgo-project/ginkgo/actions/runs/468671387
The format commit only changes the order of header, so I will merge it directly not push it again.

**Comment by upsj** [comment]
Sounds sensible, also in #691 I will replace the headers by the correct C++-style headers, so this will not be an issue in the future.

**Pull request merged**
