### PR TITLE
Merging batch-dpcpp into batch-develop

### PR DESCRIPTION
**Pull request by phu0ngng**
- [x] Matrix:
   - [x] `batch_csr_kernels` 
   -  [x] `batch_dense_kernels`
   -  [x] `batch_ell_kernels`
   -  [x] `batch_diagonal_kernels`

- [x] Preconditioner:
   - [x] `batch_identity`
   - [x] `batch_scalar_jacobi`  
   - [x] `batch_block_jacobi`: implemented, did not pass any tests, thus marked as NOT_IMPLEMENTED. There is an issue that the `warp_size` should be equal to `block_size` but the smallest possible `warp_size` in `dpcpp` is 16 which is pretty big for a batch kernel.     
  - [x] `batch_ilu`  
  - [x] `batch_ilu_isai`
  - [x] `batch_isai` 

- [x] Solver:
   -  [x] `batch_cg_kernels`
   -  [x] `batch_bicgstab_kernels` 
   -  [x] `batch_gmres_kernels`
   -  [x] `batch_direct_kernels`  
   -  [x] `batch_idr_kernels`
   -  [x] `batch_richardson_kernels`  
   -  [x] `batch_lower_trs_kernels`
   -  [x] `batch_upper_trs_kernels`.

### CODE REVIEW

**Comment by pratikvn** [comment]
format!

**Comment by phu0ngng** [comment]
format!

**Comment by phu0ngng** [comment]
format!

**Comment by pratikvn** [comment]
Closing as it is not necessary anymore.

**Pull request closed without merging**
