### PR TITLE
Release 1.8.0 to master

### PR DESCRIPTION
**Pull request by tcojean**
This should be the same as #1621 but for the master branch, including all the updated commits.

Please check the README extensively, as it is the main point of failure (changes develop -> master) together with the main CMakeLists.txt

### CODE REVIEW

**Review by MarcelKoch — APPROVED** [review]
Thanks for putting this together!

**Comment by yhmtsai** [comment]
```
diff --git a/benchmark/test/test_framework.py.in b/benchmark/test/test_framework.py.in
diff --git a/benchmark/test/test_framework.py.in b/benchmark/test/test_framework.py.in
index 48f3ca608b..62c4293e7c 100644
--- a/benchmark/test/test_framework.py.in
+++ b/benchmark/test/test_framework.py.in
@@ -22,7 +22,8 @@ denumberify_paths = [
     "rhs_norm",
     "max_relative_norm2",
 ]
-detypenameify_key_starts = ["generate(", "apply(", "advanced_apply(", "copy(", "check("]
+detypenameify_key_starts = [
+    "generate(", "apply(", "advanced_apply(", "copy(", "check("]
 empty_string_paths = ["filename"]
 empty_array_paths = [
     "recurrent_residuals",
@@ -148,9 +149,7 @@ def compare_output_impl(
         )
     )
     ignore_patterns = [
-        "This is Ginkgo",  # version numbers + tag
-        "    the .* module is",  # version numbers + tag
-        "    running with core module",  # version numbers + tag
+        "    the .* module is",  # version numbers
         "DEBUG: (begin|end  ) (allocate|free)",  # allocations
     ]
     typename_patterns = [
@@ -179,7 +178,8 @@ def compare_output_impl(
         ignore_patterns=ignore_patterns,
         replace_patterns=typename_patterns,
 empty_string_paths = ["filename"]
 empty_array_paths = [
     "recurrent_residuals",
@@ -148,9 +149,7 @@ def compare_output_impl(
         )
     )
     ignore_patterns = [
-        "This is Ginkgo",  # version numbers + tag
-        "    the .* module is",  # version numbers + tag
-        "    running with core module",  # version numbers + tag
+        "    the .* module is",  # version numbers
         "DEBUG: (begin|end  ) (allocate|free)",  # allocations
     ]
     typename_patterns = [
@@ -179,7 +178,8 @@ def compare_output_impl(
         ignore_patterns=ignore_patterns,
         replace_patterns=typename_patterns,
     )
-    expected_stdout_processed = sanitize_json_text(open(expected_stdout).read())
+    expected_stdout_processed = sanitize_json_text(
+        open(expected_stdout).read())
     expected_stderr_processed = sanitize_text(
         open(expected_stderr).read(),
         ignore_patterns=ignore_patterns,
@@ -190,7 +190,8 @@ def compare_output_impl(
         print("FAIL: stdout differs")
         print(
             "\n".join(
-                difflib.unified_diff(expected_stdout_processed, result_stdout_processed)
+                difflib.unified_diff(
+                    expected_stdout_processed, result_stdout_processed)
             )
         )
         failed = True
@@ -198,7 +199,8 @@ def compare_output_impl(
         print("FAIL: stderr differs")
         print(
             "\n".join(
-                difflib.unified_diff(expected_stderr_processed, result_stderr_processed)
+                difflib.unified_diff(
+                    expected_stderr_processed, result_stderr_processed)
             )
         )
         failed = True
```
this is diff between develop and this branch
I think the `ignore_patterns` should be the same and the changes in stderr are unnecessary
```
+This is Ginkgo 1.8.0 (master)
+    running with core module 1.8.0 (master)
```

**Comment by tcojean** [comment]
Thanks for catching this diff mike, now the diff with develop looks good. I have no idea where all this came from

**Comment by tcojean** [comment]
The format job relies on the base branch (master) which isn't the same format as develop. The format bot is incorrect. Maybe in the future we should base all GithubCI scripts on develop, like we do for e.g. the mirroring

**Comment by upsj** [comment]
I think we should try to stick with `pull_request_target` for security reasons, basing things on `develop` would be a bit harder.

In that vein, I actually have a suggestion: We would have much less work if `master` was closer to `develop` - what we could do there would be after merging the release PR into `develop`, we could create a commit setting the tag to `master` and immediately revert it, pointing `master` to the intermediate state before reversal. That way, commits between `master` and `develop` are not duplicated, and we have little to no effort in reviewing release PRs to `master`.

**Review by pratikvn — APPROVED** [review]

**Pull request merged**
