### PR TITLE
Bump copyright year to 2020

### PR DESCRIPTION
**Pull request by upsj**
This PR replaces all mentions of the year 2019 with 2020 in the license headers.
The change was auto-generated using the following commands:
```
for f in $(grep -lr 2019 .)
do
    sed -i 's/Copyright (c) 2017-2019, the Ginkgo authors/Copyright (c) 2017-2020, the Ginkgo authors/' $f
done
```

Happy new year (AoE)!

### CODE REVIEW

**Comment by tcojean** [comment]
For changing the license year, I think all that's needed is to update the main `LICENSE` file and re-run `make format`.

**Comment by upsj** [comment]
Ah right, I didn't look too closely at the `add_license.sh` details. But I guess the changes should be the same, right? Running `make format` might also introduce some additional changes since each `clang-format` version seems to have its own quirks.

**Comment by tcojean** [comment]
I would rather you try out with the script, that way we can check whether it still covers everything. One question concern the new `.inc` files. I'm not sure whether the script covers these.

**Comment by upsj** [comment]
That is a very good point! The script does cover .hpp.inc files, but we have a file that is named .hip.inc (probably by accident), that wasn't covered by the `add_license.sh` script. I guess it would make sense to add this change to this PR as well?

**Pull request merged**
