### PR TITLE
Add scaling operations for batch matrices

### PR DESCRIPTION
**Pull request by pratikvn**
~~This PR adds a batch::Diagonal matrix format, core and device kernels for the `apply(MultiVector*, MultiVector*)`. This is useful when scaling matrices and vectors that are necessary in some applications.~~

This PR now only adds the kernels and free standing functions for two-sided scaling.  

### TODO
+ [x] Add scaling kernels for batched matrices
+ [x] Check docs
+ [x] Add in_place apply core function 
+ [x] Add row, col scaling and update batch solvers to enable scaling.

### CODE REVIEW

**Comment by pratikvn** [comment]
format!

**Comment by MarcelKoch** [comment]
In the PR description you said that this PR only adds kernels and free-standing functions, but the `scale_add` and `add_scaled_identity` are member functions. Why are those members, but `two_sided_scale` not?

**Comment by MarcelKoch** [comment]
TBH, it seems like the `scale_add` and `add_scaled_identity` are not meant to be part of this PR, since the device kernels for those are not implemented.

**Comment by pratikvn** [comment]
Stale PR, superseded by #1527, but will leave the branch un-deleted to allow for testing.

**Pull request closed without merging**
