### PR TITLE
Add a `GINKGO_` prefix to all CMake variables and functions.

### PR DESCRIPTION
**Pull request by tcojean**
This MR does the same thing as #204 but for CMake. This is the starting point of a series of changes regarding CMake.

I also updated the `README.md` to add some Ginkgo CMake options which were not listed yet.

Requirements
+ [x] Merge #214 
+ [x] Rebase, check new changes and retest this MR

### CODE REVIEW

**Comment by tcojean** [comment]
In terms of conflicts, this should actually be merge-able. The only conflict is one line in GMRES #194 : the `create_test(...)` which should be changed to `ginkgo_create_test(...)` if we merge this first.

Maybe it's still safer to wait for #194 to be merged first.

**Comment by thoasm** [comment]
@tcojean I am fine with merging this PR first.
I think I can resolve the conflicts manually in GMRES.
Do you know if there are any conflicts with #198 ?

**Comment by tcojean** [comment]
None that I can think of. #198 does not touch anything CMake related at all, nor uses any CMake defined variable.

**Comment by thoasm** [comment]
Then I am fine with you merging it.

**Pull request merged**
