### PR TITLE
Generation script improvements

### LINKED ISSUE #25: Automatically comment-out example code generated by Solver/Preconditioner generator
@tcojean could we modify the solver generator script to automatically comment-out these placeholders and add `NOT_IMPLEMENTED` specifications instead?

It shouldn't be that difficult, every line containing just `{` (with no indent) is bound to be a start of function body (classes and namespaces have `{` on the same line as the name), and every line containing just `}` is bound to be end of a function (classes have `};` and namespaces `}  // namespace <name>`).

### PR DESCRIPTION
**Pull request by tcojean**
I took some time today to do the changes requested to the script so that the next solver/preconditioner/matrix addition to Ginkgo are hopefully much faster. For that, I added some new fancy things:
1. Comment out all imported code, add NOT_IMPLEMENTED and TODO items
2. Automatically add the generated files to all the CMakeLists (keep everything sorted)
3. Automatically add all the required lines to common_kernels.inc.cpp for the new solver/preconditioner/matrix. Thanks to this, the code should compile without having to do anything. 
4. I added a switch to the script to disable the automatic modifications so that it's possible to do everything by hand similarly to before if there is some sort of problem.

I would like some feedback, in particular for mac users @hartwiganzt because maybe some commands are missing or without some particular arguments.

Closes #25

### CODE REVIEW

**Comment by tcojean** [comment]
@hartwiganzt I do not understand. You mean that it does not add to files such as `gpu/test/solver/CMakeLists.txt` the new solver? It's supposed to do that, at least that parts works on my computer.

**Comment by hartwiganzt** [comment]
please try when adding a new matrix format, whether in /gpu/test/matrix/CMakeLists.txt te format is added. It is not for me.

**Comment by tcojean** [comment]
Hm, interesting, even when adding a new matrix format it works for me.

Can you add at the beginning of the script (under the first line) `set -xv` and give me the full output when you run the script?

**Comment by hartwiganzt** [comment]
It messed up ../../core/CMakeLists.txt for me - not for you?

**Comment by tcojean** [comment]
My bad, there was a subscript problem with the new version. What about now?

**Comment by tcojean** [comment]
I updated it again. The error message for the awk is very cryptic so it's hard to guess. Maybe this new version works better.

**Comment by tcojean** [comment]
@hartwiganzt everything should work now. Thanks a lot for your test, it looks like the GPU kernels for CSR (`csr_kernels.cu`) used `};` to close function definitions instead of simple `}`, which made the script not work properly. I fixed the CSR definitions to make it work.

I also realised there was a problem with GPU kernel files which can have either `.cpp` or `.cu` extension. I have fixed this by adding some detection in the script.

**Comment by hartwiganzt** [comment]
Works fine now. Thanks!
Only, there is still the bug in the cgs kernel tester. Does it need to be rebased? It says: 
"This branch has no conflicts with the base branch"
I am confused.

**Comment by hartwiganzt** [comment]
Well, if you can merge this pull request, we are fine. I then just discard my branch... but sure, you can look into it.

**Comment by gflegar** [comment]
Did  you look into it? If so, this can be merged - I'm fine with having only 1 review on stuff that is not part of the library itself, but a utility tool.

**Pull request merged**
