### PR TITLE
add benchmark.sh

### PR DESCRIPTION
**Pull request by yhmtsai**
the script is for the benchmark of spmv and solver

### CODE REVIEW

**Comment by gflegar** [comment]
Uhm, not sure I get it, I though it downloads the matrices from the suite sparse web site?

**Comment by hartwiganzt** [comment]
@yhmtsai the question is: can this dataset stay there for long time? maybe we want to find a different location - e.g. on SCC resources.

**Comment by yhmtsai** [comment]
No.
And it needs the access to the workstation.
I can write the script which downloads matrices from the suite sparse.
Putting them on the SCC resources is also fine.

**Comment by gflegar** [comment]
Already on it: https://github.com/ginkgo-project/ssget

**Comment by hartwiganzt** [comment]
I think this is no longer needed, correct?

**Comment by gflegar** [comment]
Yes, closing this.

**Pull request closed without merging**
