### PR TITLE
Split common kernels

### PR DESCRIPTION
**Pull request by tcojean**
Separate the two existing implementation types:
+ CUDA/HIP kernels into `cuda_hip`
+ The unified lambda-based interface into `unified`.

Depends on #854

### CODE REVIEW

**Comment by tcojean** [comment]
format!

**Review by upsj — APPROVED** [review]
LGTM! We may need to adapt the include guards for the kernel_launch* files to reflect the correct path? Curious why the formatting script didn't pick them up.

**Review by pratikvn — APPROVED** [review]
LGTM!

**Review by yhmtsai — APPROVED** [review]
LGTM. `FORMAT_HEADER_REGEX` in bot-pr-format-base.sh does not consider common, so it only apply format not format_header

**Pull request merged**
