### PR TITLE
Improve gdb pretty-printer for newer libstdc++

### PR DESCRIPTION
**Pull request by upsj**
These changes were adapted from the most recent gcc source

### CODE REVIEW

**Review by tcojean — APPROVED** [review]
LGTM. Maybe cite this or related as source

**Review by yhmtsai — APPROVED** [review]
I only check whether the changes match the version @tcojean provides.
I have the same comment as @tcojean

**Comment by upsj** [comment]
rebase!

**Comment by upsj** [comment]
@tcojean thanks for finding the source :)

**Pull request merged**
