### PR TITLE
Add rocthrust through cmake

### PR DESCRIPTION
**Pull request by MarcelKoch**
This PR uses CMake to find and add rocthrust. This fixes the spack issue reported in https://github.com/spack/spack/pull/44923.

### CODE REVIEW

**Review by pratikvn — APPROVED** [review]

**Review by yhmtsai — APPROVED** [review]

**Comment by MarcelKoch** [comment]
I will wait merging this until https://github.com/spack/spack/pull/45791 is resolved. Maybe there is still something missing.

**Comment by yhmtsai** [comment]
question: do you create a patch in spack package? or should we release 1.8.1

**Comment by MarcelKoch** [comment]
There is a patch for the spack package. I think there is no need for an 1.8.1 otherwise.

**Comment by MarcelKoch** [comment]
The spack CI passed, so I consider this PR to be complete.

**Review by upsj — APPROVED** [review]

**Pull request merged**
