### PR TITLE
Improve benchmark output

### PR DESCRIPTION
**Pull request by upsj**
This PR adds two matrix dimension output for `matrix_statistics`

### CODE REVIEW

**Comment by MarcelKoch** [comment]
I think the first part of this PR is rather uncontroversial, but for the second part I'm not so sure. Would it make sense to split this PR, as the two parts already have few things in common?

**Comment by upsj** [comment]
@MarcelKoch you're of course totally correct, I was just a bit lazy :)

**Review by MarcelKoch — APPROVED** [review]
LGTM, seems like a useful addition

**Review by yhmtsai — APPROVED** [review]
LGTM

**Pull request merged**
