### PR TITLE
Fix some sanitizer failures

### PR DESCRIPTION
**Pull request by upsj**
This PR fixes a (probably harmless) UBSAN/ASAN overflow/out-of-bounds memory access in ISAI and an uninitialized memory read in IDR. Additionally, it warns when using a build type that is not supported by the compiler (an issue found by @fritzgoebel), and runs the `cuda-memcheck` tasks on amdci.

### CODE REVIEW

**Review by fritzgoebel — APPROVED** [review]
lgtm

**Review by pratikvn — APPROVED** [review]
LGTM!

**Comment by upsj** [comment]
rebase!

**Review by thoasm — APPROVED** [review]
LGTM!

**Review by tcojean — APPROVED** [review]
LGTM.

**Pull request merged**
