### PR TITLE
SYCL deprecation fixes

### PR DESCRIPTION
**Pull request by upsj**
Fixes the deprecation warnings for accessors to local memory

### CODE REVIEW

**Comment by upsj** [comment]
I've decided the complexity involved in sub-devices just to get #1373 working on SYCL CPUs isn't worth it yet, so I'll be removing those changes, only fixing the deprecation warnings

**Comment by pratikvn** [comment]
We should either remove bump the SYCL version support or create a special case for it, as this update [currently breaks for SYCL 2022-1](https://gitlab.com/ginkgo-project/ginkgo-public-ci/-/jobs/6271510855).

**Comment by upsj** [comment]
There are some additional issues with `cooperative_groups::ballot` using `reduce_over_group` slightly wrong, but that can be fixed easily

**Review by yhmtsai — COMMENTED** [review]
Is the PR description old? I do not see the changes for device.
LGTM in code itself.
However, I would keep intel compiler 2022 as the 2023 does not work properly.
you can make local_accessor function to the old accessor with target::local when it is not supported

**Comment by rscohn2** [comment]
These changes are needed to build ginkgo with icpx 2024.1 & later.

**Comment by yhmtsai** [comment]
Thanks for updating.
ReadME version support is not updated.
you can also change the image `ginkgohub/oneapi:2024.0.2.20231213` to `ginkgohub/oneapi:latest`

**Review by pratikvn — APPROVED** [review]

**Review by yhmtsai — APPROVED** [review]

**Pull request merged**
