### PR TITLE
Release 1.7.0 to develop

### PR DESCRIPTION
**Pull request by tcojean**
Release 1.7.0 and update the Changelog.

See #1451

### CODE REVIEW

**Review by yhmtsai — APPROVED** [review]
need to provide the short description for the pr.

**Review by upsj — APPROVED** [review]

**Comment by upsj** [comment]
Should we also update the version to 1.8.0?

**Comment by tcojean** [comment]
> Should we also update the version to 1.8.0?

I wanted to do that in another PR so that these two different things aren't merged together in the history. See #1455

**Comment by tcojean** [comment]
It's only documentation changes, so I just merged.

**Pull request merged**
