### PR TITLE
Fix hwloc version detection

### PR DESCRIPTION
**Pull request by upsj**
The version detection chokes on versions that actually contain alphabet characters instead of the common 0-9. This never came up because we commonly only use versions up to 2.9, but it fails with 1.11.

### CODE REVIEW

**Review by yhmtsai — APPROVED** [review]
LGTM.
Just a side note: outputformat is supported from cmake 3.13

**Review by pratikvn — APPROVED** [review]
Thanks for fixing this. LGTM! I would also maybe go ahead and update the License in the top of the file.

**Review by tcojean — APPROVED** [review]
LGTM.

**Comment by upsj** [comment]
rebase!

**Pull request merged**
