### PR TITLE
squeeze memory dispatch code

### PR DESCRIPTION
**Pull request by yhmtsai**
This PR squeezes the dispatch code in memory. It is done in #1257 by @MarcelKoch. 
I extract them here and ensure it is good to change or not.

### CODE REVIEW

**Review by upsj — APPROVED** [review]
LGTM!

**Review by MarcelKoch — COMMENTED** [review]
Since I originally wrote this, I won't review it. I just wanted to confirm that this is the change I intended to make.

**Comment by yhmtsai** [comment]
I also go through it, so @MarcelKoch maybe approves it on my behalf?

**Review by MarcelKoch — APPROVED** [review]
@yhmtsai That makes sense.

**Pull request merged**
