### PR TITLE
Update version output

### PR DESCRIPTION
**Pull request by gfcas**
This adds a whitespace for nicely format the version output.

### CODE REVIEW

**Review by tcojean — APPROVED** [review]
LGTM!

I think technically you still need to add yourself to contributors.txt?

Also, looking at this I realized we do not print the DPC++ version which is now available. If you feel up to the task please go ahead, otherwise this is perfectly fine we can do it in one of the ongoing DPC++ PR as well.

**Review by yhmtsai — APPROVED** [review]
LGTM. 
I totally agree what @tcojean said.
With your final modification, could you also rebase your branch to the latest develop, such that we have linear history on develop branch?

**Comment by yhmtsai** [comment]
check-format!

**Comment by yhmtsai** [comment]
I am not sure whether it can check the pr from outside. Just give a try.

**Comment by gfcas** [comment]
> 
> 
> I think technically you still need to add yourself to contributors.txt?

If you think it is justified for this very small contribution? Should I include the modified file in this PR?

> 
> Also, looking at this I realized we do not print the DPC++ version which is now available. If you feel up to the task please go ahead, otherwise this is perfectly fine we can do it in one of the ongoing DPC++ PR as well.

Yes, you are right. I tried to add the version number for DPCPP. Tomorrow morning I'll test it, i.e., if the table is output nicely and completely.

What do you mean with 'check-format!' ? Was this meant for me?

**Comment by gfcas** [comment]
> With your final modification, could you also rebase your branch to the latest develop, such that we have linear history on develop branch?

The branch should be already rebased to 'develop' (just checked).

**Comment by yhmtsai** [comment]
No, `check-format!` is the functionality of ginkgo bot to check the format of this pr.
it seems to only apply for our side.

**Comment by upsj** [comment]
The script ran through perfectly fine, you just don't see any output if it succeeds. You can check that in the `Actions` tab.

**Comment by upsj** [comment]
check-format!

**Comment by yhmtsai** [comment]
the check-format is skipped, I think it does not really check?

**Comment by upsj** [comment]
Those are two different actions/triggers: The one you see below is only triggered by pushes from authorized people, and [this one](https://github.com/ginkgo-project/ginkgo/actions/runs/980202579) triggered by comments from authorized people. We don't set status flags for the comment version.

**Comment by tcojean** [comment]
> > I think technically you still need to add yourself to contributors.txt?
> 
> If you think it is justified for this very small contribution? Should I include the modified file in this PR?
> 

I think it would be better if you can add yourself. The changes are minor, but in terms of license management that makes since simpler, for one.

**Review by pratikvn — APPROVED** [review]
Thanks Fabian! Please add yourself to the contributors.txt list as well. It is required from our end for licensing purposes.

**Comment by gfcas** [comment]
Thank you all! I just install the new version and test the output locally.

**Comment by gfcas** [comment]
Yeah, looks nicely now:
```
This is Ginkgo 1.4.0 (develop)
    running with core module 1.4.0 (develop)
    the reference module is  1.4.0 (develop)
    the OpenMP    module is  1.4.0 (develop)
    the CUDA      module is  1.4.0 (develop)
    the HIP       module is  not compiled
    the DPCPP     module is  not compiled
```

**Pull request merged**
