### PR TITLE
Bump the current version to 1.4.0

### PR DESCRIPTION
**Pull request by tcojean**
This will be the next master release.

### CODE REVIEW

**Review by upsj — APPROVED** [review]

**Review by pratikvn — APPROVED** [review]

**Review by nbeams — APPROVED** [review]
Thanks!

**Review by yhmtsai — APPROVED** [review]
LGTM. Do you think we should also include the #731 for memory leak?

**Comment by tcojean** [comment]
@yhmtsai This is not a proper release per se, this is only for convenience. It's fine that #731 or any other PR is merged afterwards. This is done so that we can identify the already done changes compared to 1.3.0 as part of the future 1.4.0, as well as the coming changes. I will consider actually releasing 1.4.0 when we have more DPC++ features available in `develop`.

**Review by thoasm — APPROVED** [review]
LGTM!

**Comment by yhmtsai** [comment]
@tcojean I see. Thanks!

**Pull request merged**
