### PR TITLE
Remove JOSS job

### PR DESCRIPTION
**Pull request by pratikvn**
Remove the job that compiled the paper for JOSS. The files used (`doc/joss/*`) have still been left as is for reference, but I think the job is not needed anymore.

### CODE REVIEW

**Review by upsj — APPROVED** [review]
LGTM! There are some people approaching software publications as "living papers" that evolve alongside the code and documentation, but I don't think we need to do that with the JOSS paper.

**Comment by yhmtsai** [comment]
I think it is the JOSS idea, right?
How does it work with changed content? Originally, I thought we only need to update it by ourselve. Do we need to request a review from JOSS site?
We should update some outdated information like we use another json package not rapidjson anymore.

**Comment by pratikvn** [comment]
I dont think they have support for version updates like Zenodo. It would have to be a new paper (with new reviews and so on), which I think is possible, but I dont think we need to do that, as I dont see any real benefits from that.

**Comment by yhmtsai** [comment]
okay, it need to wait until #1747 is merged

**Pull request merged**
