### PR TITLE
MPI branch updates

### PR DESCRIPTION
**Pull request by MarcelKoch**
This PR adds some fixes/additions from the branch `mpi-for-hyteg`.

List of changes:
- additional mpi bindings (all_gather, scan)
- example which reads matrix from local data
- adds partition member to distributed matrix and vector
- more comprehensive tests
- adds a local-to-global index mapping (naming could be changed)
- allows conversion between int32<->int64 arrays 
- changes default comm/window to `MPI_[COMM|WIN]_NULL`

Most of the remaining changes in `mpi-for-hyteg` concern the conversion `distributed::matrix -> matrix::csr`, where the local matrices are combined on one rank.

### CODE REVIEW

**Comment by pratikvn** [comment]
If you rebase this on the current mpi-base-dist-mat, then we can try to get this merged ?

**Comment by MarcelKoch** [comment]
I've rebased it onto the current `mpi-base-dist-mat`. There are still some issues with the failing CI, but that can be postponed.

**Comment by MarcelKoch** [comment]
format!

**Review by pratikvn — APPROVED** [review]
@MarcelKoch , I think everything's okay from my side now, so feel free to merge this PR once the CI passes.

**Pull request merged**
