### PR TITLE
Fix minor example issues

### PR DESCRIPTION
**Pull request by gfcas**
Clearify the functionality of a dealii function in the external-lib-example.

### CODE REVIEW

**Comment by gfcas** [comment]
Can you please explain me, what is the app_exec in poisson-solver. I do not understand it, for commenting.

**Comment by upsj** [comment]
The "application" code is CPU only, so it needs to use the host executor accessible via `exec->get_master()` instead of the device executor.

**Comment by gfcas** [comment]
> The "application" code is CPU only, so it needs to use the host executor accessible via `exec->get_master()` instead of the device executor.

Thanks, this means for the external library code I only need to run the solver on exec (GPU) not the other parts:
```cpp
auto             b       = vec::create(exec,
                         gko::dim<2>(num_rows, 1),
                         val_array::view(exec, num_rows, rhs.data()),
                         1);
    auto             x       = vec::create(exec, gko::dim<2>(num_rows, 1));
    auto             A       = mtx::create(exec,
                         gko::dim<2>(num_rows),
                         system_matrix.n_nonzero_elements());
```
Here I would everywhere replace it with app_exec.

This is taken from external-library example, as I want to integrate it in dealii.

**Review by MarcelKoch — APPROVED** [review]

**Review by upsj — APPROVED** [review]

**Comment by upsj** [comment]
label!

**Comment by upsj** [comment]
check-format!

**Review by tcojean — APPROVED** [review]

**Pull request merged**
